### ISSUE TITLE
Wrong number of pairs & The code is running forever

### ISSUE THREAD

**Issue by LLeiSong** [Circuitscape/Circuitscape.jl#114]
Hi, 
I tried the Circuitscape.jl yesterday. Got some issues:
1. The code get the total number of pair solves is 1, but in fact it should be 78.
2. Solving this pair takes forever.  The code ran for the whole night and didn't get anything. I think there is not right.

I tried the same data using GUI. Even though it is super slow, It works well. So I guess my habitat and patch data are fine. Then I was wondering did I do something wrong to run the Circuitscape.jl?

Appreciate any help.

**Comment by ranjanan** [comment]
Hi @LLeiSong is there any way you can share your problem files with me (INI, cell map, etc) so I can debug this?

**Comment by LLeiSong** [comment]
@ranjanan, Sure. Sorry I forgot. Thanks very much for your help. Here are the files that I used. https://www.dropbox.com/sh/04d1a5yj1f6auet/AABvXC9ccNaLL6lZVcSWHN6Ba?dl=0

**Comment by ranjanan** [comment]
Thank you, I will get back to you on this as  soon as I can.

**Comment by ranjanan** [comment]
Could you post the output you are getting from the software too please? That would be helpful for me.

**Comment by ranjanan** [comment]
@LLeiSong I just ran your problem and the first thing I noticed that the logging is wrong. I have improved the logging through #117. 

Could you run this from your Julia prompt: 
```julia
Pkg.checkout("Circuitscape")
```
and then restart Julia and try? You should see 78 solves. 

Another thing I noticed was that your problem was of the size ~36m, which is probably a bit on the higher side for the cholmod solver. Could you try setting `solver = cg+amg` in your INI file?

Let me know if this helps. Also, as I mentioned in https://github.com/Circuitscape/Circuitscape.jl/issues/109#issuecomment-384337377, you might need to generate cumulative current maps after the run, while I figure out how to generate them during each run. 

Please let me knows how it goes.

**Comment by rmarrotte** [comment]
Hi,
I have the same issue. I have over 200,000 pairs to solve and it only runs 416 of them... Once it's done it just throws in one of the pair IDs or something as the effective resistance. If you run the same INI file with the CS gui it runs all pairs found in the include file.
Thanks
Robby

**Comment by LLeiSong** [comment]
@ranjanan thank you so much. I reinstall the package and tried again. Now it can recognize all the pairs. I think it is working well. But my computer sucks, it is super slow. I am not sure it is normal or not. I will follow up.

**Comment by ranjanan** [comment]
@LLeiSong I checked with the Python package and the solver seems to fail for the pairs. Perhaps you should also check if there is something amiss with your input.

**Comment by LLeiSong** [comment]
@ranjanan this is also my concern. I will check the data carefully. Will let you know what's going on there.

**Comment by ranjanan** [comment]
@LLeiSong sure. I'm closing this issue because the original bug report has been fixed. Feel free to open new ones for new issues. Thanks!
