### ISSUE TITLE
resistance_3columns file

### ISSUE THREAD

**Issue by ramonwilk** [Circuitscape/Circuitscape.jl#315]
Hi, I'm trying to run  a one-to-all resistance analyse  in Circuitscape.jl (julia> Pkg.add(PackageSpec(name="Circuitscape", rev="master"))), but the output file doesn't return the "resistance_3columns file". 

When I did run a pairwise analysis the program returns all files normally.

Can you help me, please?

**Comment by vlandau** [comment]
@ramonwilk because of the way one-to-all works, you don't get pairwise resistances for each pair of nodes -- in one-to-all, for a given iteration, one node is set as a source and all other nodes are set to ground, so an effective resistance is not calculated for each node pair. Hope that helps. More information on the different modes is available [here](https://docs.circuitscape.org/Circuitscape.jl/latest/usage/#Calculation-modes) in the docs.

I'm going to close this issue since one-to-all is not intended to create effected resistances (resistance_3columns), but please feel free to continue to comment on this thread with any questions!
